### ISSUE TITLE
Question: setting macOS

### ISSUE THREAD

**Issue by rlodina** [sedenardi/node-caldav-adapter#5]
Hello.

I run sample code. 

I'm getting rid of something ... I can't configure the CalDav account (macOS Catalina - 10.15.5): 
![caldav-account-setup](https://user-images.githubusercontent.com/1677944/86049193-63a80480-ba5a-11ea-9b98-9b278a8e1e93.png)

On Sign In the request is send to server:

``` XML
<?xml version="1.0" encoding="UTF-8"?>
<A:propfind xmlns:A="DAV:">
  <A:prop>
    <A:principal-URL/>
  </A:prop>
</A:propfind>
```

Server (node -> v14.0.0) always respond: `Unauthorized` - I catch comunication with mitmroxy.
If is change `Server path` to something else eq: `/calendar` the response is `outside caldav server`

an idea where I was wrong ...

Thank you

**Comment by sedenardi** [comment]
Hi there. From my testing, I believe you have to use an HTTPS connection with a valid (on your machine) certificate. So you can either create a trusted self-signed cert for your localhost, or use a service like `ngrok` to create a secure connection to your local machine.

I've updated the README to clarify that point.
